version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.12
    ports:
      - "52883:1883"
  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    volumes:
    - ./api:/app
    ports:
      - "3333:3333"

  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
        - ./client:/app
        - /app/node_modules
    ports:
      - "3000:3000"
