version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - "1884:1883"